### ISSUE TITLE
async is a reserved keyword - import fails

### ISSUE THREAD

**Issue by mfergus1** [TheJumpCloud/jcapi-python#22]
Hi there - 
I am trying to use jcapiv2 (with python3.7) and have 
```import jcapiv2
from jcapiv2.rest import ApiException
```
and get:  
```
File "/Users/miaferguson/Workspace/auditing/lib/python3.7/site-packages/jcapiv2/api/active_directory_api.py", line 149
    async=params.get('async'),
        ^
SyntaxError: invalid syntax
```

**Comment by thinkterry** [comment]
Thanks for letting us know, @mfergus1! We've looked into this issue and believe it to be an incompatibility between the version of Swagger Codegen we were using, 2.3.1, and Python 3.7, [which made `async` a reserved keyword](https://docs.python.org/release/3.7.0/whatsnew/3.7.html). We've just released [3.0.0](https://github.com/TheJumpCloud/jcapi-python/releases/tag/3.0.0), which upgrades Swagger Codegen to 2.4.2 and [should add support for Python 3.7](https://github.com/swagger-api/swagger-codegen/releases/tag/v2.4.0). Let us know if this resolves your issue or if there are additional steps we need to take.
